import type { Metadata } from 'next';

import './globals.css';

import { Container, CssBaseline } from '@mui/material';

import Header from './components/header';
import Providers from './providers';
import checkAuthentication from './auth/checkAuthentication';
import logout from './auth/logout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAuthenticated = await checkAuthentication();

  return (
    <html lang="en">
      <body>
        <Providers isAuthenticated={isAuthenticated}>
          <CssBaseline />
          <Header logout={logout} />
          <Container className="mt-10">{children}</Container>
        </Providers>
      </body>
    </html>
  );
}
